### ISSUE TITLE
Teensy 4.0 port

### ISSUE THREAD

**Issue by bvanpoortvliet** [claudeheintz/LXTeensy3DMX_Library#2]
Hi Claude,

Since the teensy 4.0 is out, are you planning to port your libraries to this board, or could you perhaps give me some pointers on how to do it myself. I'd love to use your libraries with this board but now it won't compile.

The error I'm getting when trying to compile the Teensy3ArtNetSACN2Universes_rdm example is: 

Documents/Arduino/libraries/LXTeensy3DMX_Library/src/LXTeensy3DMX.h:62:21: fatal error: kinetis.h: No such file or directory.

Any help would be appreciated.

**Comment by claudeheintz** [comment]
There is now a new repository named LXTeensy4DMX_Library which has the first draft of a DMX driver for Teensy4.

The output of DMX works.  Input and RDM are untested at the moment.

**Comment by claudeheintz** [comment]
LXTeensy4DMX_Library has now been tested with output, input and RDM.  It functions essentially identically with LXTeensy3DMX, except the UART pins are slightly different but follow the Teensy 4.0 pin diagram (see the readme.md file).
